### funcao para varrer o banco de dados e consultar o cadastro de professores no sistema ###
def estatisticasProfessor():      
    import sqlite3
    conectar = sqlite3.connect("bancodeDados.db") 
    interagir = conectar.cursor()
    print('Relação de professores cadastrados no sistema')
    print('--'*26)
    for registroProfessor in interagir.execute("SELECT * FROM professor ORDER BY nomeProfessor"):
        print("Nome do professor(a): {}".format(registroProfessor[0]))
        print("Disciplina: {}".format(registroProfessor[1]))
### funcoes que varrem os bancos de dados e consultar as turams cadastradas no sistema ###
def estatisticasPrimeiroAnoA():
    print('Notas cadastradas e situação para o primeiro ano turma A: ')    
    import sqlite3
    conectar = sqlite3.connect("bancodeDados.db") 
    interagir = conectar.cursor()
    for registroAluno in interagir.execute("SELECT * FROM primeiroanoa ORDER BY nomealuno"):
        print('Nome do aluno(a): {}'.format(registroAluno[0]))        
        print("Português:")
        print("1ª Nota: {}".format(registroAluno[1]))
        print("2ª Nota: {}".format(registroAluno[2]))
        print("3ª Nota: {}".format(registroAluno[3]))
        print("4ª Nota: {}".format(registroAluno[4]))
        print("Média: {}".format(registroAluno[17]))
        print("Situação: {}".format(registroAluno[21]))
        print("Matemática:")
        print("1ª Nota: {}".format(registroAluno[5]))
        print("2ª Nota: {}".format(registroAluno[6]))
        print("3ª Nota: {}".format(registroAluno[7]))
        print("4ª Nota: {}".format(registroAluno[8]))
        print("Média: {}".format(registroAluno[18]))
        print("Situação: {}".format(registroAluno[22]))
        print("Geografia:")
        print("1ª Nota: {}".format(registroAluno[9]))
        print("2ª Nota: {}".format(registroAluno[10]))
        print("3ª Nota: {}".format(registroAluno[11]))
        print("4ª Nota: {}".format(registroAluno[12]))
        print("Média: {}".format(registroAluno[19]))
        print("Situação: {}".format(registroAluno[23]))
        print("História:")
        print("1ª Nota: {}".format(registroAluno[13]))
        print("2ª Nota: {}".format(registroAluno[14]))
        print("3ª Nota: {}".format(registroAluno[15]))
        print("4ª Nota: {}".format(registroAluno[16]))
        print("Média: {}".format(registroAluno[20]))
        print("Situação: {}".format(registroAluno[24]))     
        print('--'*26)
    print('Retornando ao menu anterior...')
    import coordenadorPedagogico
    coordenadorPedagogico.menuEstatisticasAlunos()
def estatisticasPrimeiroAnoB():
    import sqlite3
    conectar = sqlite3.connect("bancodeDados.db") 
    interagir = conectar.cursor()
    for registroAluno in interagir.execute("SELECT * FROM primeiroanob ORDER by nomealuno"):
        print('Nome do aluno(a): {}'.format(registroAluno[0]))        
        print("Português:")
        print("1ª Nota: {}".format(registroAluno[1]))
        print("2ª Nota: {}".format(registroAluno[2]))
        print("3ª Nota: {}".format(registroAluno[3]))
        print("4ª Nota: {}".format(registroAluno[4]))
        print("Média: {}".format(registroAluno[17]))
        print("Matemática:")
        print("1ª Nota: {}".format(registroAluno[5]))
        print("2ª Nota: {}".format(registroAluno[6]))
        print("3ª Nota: {}".format(registroAluno[7]))
        print("4ª Nota: {}".format(registroAluno[8]))
        print("Média: {}".format(registroAluno[18]))
        print("Geografia:")
        print("1ª Nota: {}".format(registroAluno[9]))
        print("2ª Nota: {}".format(registroAluno[10]))
        print("3ª Nota: {}".format(registroAluno[11]))
        print("4ª Nota: {}".format(registroAluno[12]))
        print("Média: {}".format(registroAluno[19]))
        print("História:")
        print("1ª Nota: {}".format(registroAluno[13]))
        print("2ª Nota: {}".format(registroAluno[14]))
        print("3ª Nota: {}".format(registroAluno[15]))
        print("4ª Nota: {}".format(registroAluno[16]))
        print("Média: {}".format(registroAluno[20]))     
        print('--'*26)
    print('Retornando ao menu anterior...')
    import coordenadorPedagogico
    coordenadorPedagogico.menuEstatisticasAlunos()
def estatisticasPrimeiroAnoC():
    import sqlite3
    conectar = sqlite3.connect("bancodeDados.db") 
    interagir = conectar.cursor()
    for registroAluno in interagir.execute("SELECT * FROM primeiroanoc ORDER by nomealuno"):
        print('Nome do aluno(a): {}'.format(registroAluno[0]))        
        print("Português:")
        print("1ª Nota: {}".format(registroAluno[1]))
        print("2ª Nota: {}".format(registroAluno[2]))
        print("3ª Nota: {}".format(registroAluno[3]))
        print("4ª Nota: {}".format(registroAluno[4]))
        print("Média: {}".format(registroAluno[17]))
        print("Matemática:")
        print("1ª Nota: {}".format(registroAluno[5]))
        print("2ª Nota: {}".format(registroAluno[6]))
        print("3ª Nota: {}".format(registroAluno[7]))
        print("4ª Nota: {}".format(registroAluno[8]))
        print("Média: {}".format(registroAluno[18]))
        print("Geografia:")
        print("1ª Nota: {}".format(registroAluno[9]))
        print("2ª Nota: {}".format(registroAluno[10]))
        print("3ª Nota: {}".format(registroAluno[11]))
        print("4ª Nota: {}".format(registroAluno[12]))
        print("Média: {}".format(registroAluno[19]))
        print("História:")
        print("1ª Nota: {}".format(registroAluno[13]))
        print("2ª Nota: {}".format(registroAluno[14]))
        print("3ª Nota: {}".format(registroAluno[15]))
        print("4ª Nota: {}".format(registroAluno[16]))
        print("Média: {}".format(registroAluno[20]))     
        print('--'*26)
    print('Retornando ao menu anterior...')
    import coordenadorPedagogico
    coordenadorPedagogico.menuEstatisticasAlunos()
def estatisticasSegundoAnoA():
    import sqlite3
    conectar = sqlite3.connect("bancodeDados.db") 
    interagir = conectar.cursor()
    for registroAluno in interagir.execute("SELECT * FROM segundoanoa ORDER by nomealuno"):
        print('Nome do aluno(a): {}'.format(registroAluno[0]))        
        print("Português:")
        print("1ª Nota: {}".format(registroAluno[1]))
        print("2ª Nota: {}".format(registroAluno[2]))
        print("3ª Nota: {}".format(registroAluno[3]))
        print("4ª Nota: {}".format(registroAluno[4]))
        print("Média: {}".format(registroAluno[17]))
        print("Matemática:")
        print("1ª Nota: {}".format(registroAluno[5]))
        print("2ª Nota: {}".format(registroAluno[6]))
        print("3ª Nota: {}".format(registroAluno[7]))
        print("4ª Nota: {}".format(registroAluno[8]))
        print("Média: {}".format(registroAluno[18]))
        print("Geografia:")
        print("1ª Nota: {}".format(registroAluno[9]))
        print("2ª Nota: {}".format(registroAluno[10]))
        print("3ª Nota: {}".format(registroAluno[11]))
        print("4ª Nota: {}".format(registroAluno[12]))
        print("Média: {}".format(registroAluno[19]))
        print("História:")
        print("1ª Nota: {}".format(registroAluno[13]))
        print("2ª Nota: {}".format(registroAluno[14]))
        print("3ª Nota: {}".format(registroAluno[15]))
        print("4ª Nota: {}".format(registroAluno[16]))
        print("Média: {}".format(registroAluno[20]))     
        print('--'*26)
    print('Retornando ao menu anterior...')
    import coordenadorPedagogico
    coordenadorPedagogico.menuEstatisticasAlunos()   
def estatisticasSegundoAnoB():
    import sqlite3
    conectar = sqlite3.connect("bancodeDados.db") 
    interagir = conectar.cursor()
    for registroAluno in interagir.execute("SELECT * FROM segundoanob ORDER by nomealuno"):
        print('Nome do aluno(a): {}'.format(registroAluno[0]))        
        print("Português:")
        print("1ª Nota: {}".format(registroAluno[1]))
        print("2ª Nota: {}".format(registroAluno[2]))
        print("3ª Nota: {}".format(registroAluno[3]))
        print("4ª Nota: {}".format(registroAluno[4]))
        print("Média: {}".format(registroAluno[17]))
        print("Matemática:")
        print("1ª Nota: {}".format(registroAluno[5]))
        print("2ª Nota: {}".format(registroAluno[6]))
        print("3ª Nota: {}".format(registroAluno[7]))
        print("4ª Nota: {}".format(registroAluno[8]))
        print("Média: {}".format(registroAluno[18]))
        print("Geografia:")
        print("1ª Nota: {}".format(registroAluno[9]))
        print("2ª Nota: {}".format(registroAluno[10]))
        print("3ª Nota: {}".format(registroAluno[11]))
        print("4ª Nota: {}".format(registroAluno[12]))
        print("Média: {}".format(registroAluno[19]))
        print("História:")
        print("1ª Nota: {}".format(registroAluno[13]))
        print("2ª Nota: {}".format(registroAluno[14]))
        print("3ª Nota: {}".format(registroAluno[15]))
        print("4ª Nota: {}".format(registroAluno[16]))
        print("Média: {}".format(registroAluno[20]))     
        print('--'*26)
    print('Retornando ao menu anterior...')
    import coordenadorPedagogico
    coordenadorPedagogico.menuEstatisticasAlunos()    
def estatisticasSegundoAnoC():
    import sqlite3
    conectar = sqlite3.connect("bancodeDados.db") 
    interagir = conectar.cursor() 
    for registroAluno in interagir.execute("SELECT * FROM segundoanoc ORDER by nomealuno"):
        print('Nome do aluno(a): {}'.format(registroAluno[0]))        
        print("Português:")
        print("1ª Nota: {}".format(registroAluno[1]))
        print("2ª Nota: {}".format(registroAluno[2]))
        print("3ª Nota: {}".format(registroAluno[3]))
        print("4ª Nota: {}".format(registroAluno[4]))
        print("Média: {}".format(registroAluno[17]))
        print("Matemática:")
        print("1ª Nota: {}".format(registroAluno[5]))
        print("2ª Nota: {}".format(registroAluno[6]))
        print("3ª Nota: {}".format(registroAluno[7]))
        print("4ª Nota: {}".format(registroAluno[8]))
        print("Média: {}".format(registroAluno[18]))
        print("Geografia:")
        print("1ª Nota: {}".format(registroAluno[9]))
        print("2ª Nota: {}".format(registroAluno[10]))
        print("3ª Nota: {}".format(registroAluno[11]))
        print("4ª Nota: {}".format(registroAluno[12]))
        print("Média: {}".format(registroAluno[19]))
        print("História:")
        print("1ª Nota: {}".format(registroAluno[13]))
        print("2ª Nota: {}".format(registroAluno[14]))
        print("3ª Nota: {}".format(registroAluno[15]))
        print("4ª Nota: {}".format(registroAluno[16]))
        print("Média: {}".format(registroAluno[20]))     
        print('--'*26)
    print('Retornando ao menu anterior...') 
    import coordenadorPedagogico
    coordenadorPedagogico.menuEstatisticasAlunos()      
def estatisticasTerceiroAnoA():
    import sqlite3
    conectar = sqlite3.connect("bancodeDados.db") 
    interagir = conectar.cursor()
    for registroAluno in interagir.execute("SELECT * FROM terceiroanoa ORDER by nomealuno"):
        print('Nome do aluno(a): {}'.format(registroAluno[0]))        
        print("Português:")
        print("1ª Nota: {}".format(registroAluno[1]))
        print("2ª Nota: {}".format(registroAluno[2]))
        print("3ª Nota: {}".format(registroAluno[3]))
        print("4ª Nota: {}".format(registroAluno[4]))
        print("Média: {}".format(registroAluno[17]))
        print("Matemática:")
        print("1ª Nota: {}".format(registroAluno[5]))
        print("2ª Nota: {}".format(registroAluno[6]))
        print("3ª Nota: {}".format(registroAluno[7]))
        print("4ª Nota: {}".format(registroAluno[8]))
        print("Média: {}".format(registroAluno[18]))
        print("Geografia:")
        print("1ª Nota: {}".format(registroAluno[9]))
        print("2ª Nota: {}".format(registroAluno[10]))
        print("3ª Nota: {}".format(registroAluno[11]))
        print("4ª Nota: {}".format(registroAluno[12]))
        print("Média: {}".format(registroAluno[19]))
        print("História:")
        print("1ª Nota: {}".format(registroAluno[13]))
        print("2ª Nota: {}".format(registroAluno[14]))
        print("3ª Nota: {}".format(registroAluno[15]))
        print("4ª Nota: {}".format(registroAluno[16]))
        print("Média: {}".format(registroAluno[20]))     
        print('--'*26)
    print('Retornando ao menu anterior...') 
    import coordenadorPedagogico
    coordenadorPedagogico.menuEstatisticasAlunos()   
def estatisticasTerceiroAnoB():
    import sqlite3
    conectar = sqlite3.connect("bancodeDados.db") 
    interagir = conectar.cursor()
    for registroAluno in interagir.execute("SELECT * FROM terceiroanob ORDER by nomealuno"):
        print('Nome do aluno(a): {}'.format(registroAluno[0]))        
        print("Português:")
        print("1ª Nota: {}".format(registroAluno[1]))
        print("2ª Nota: {}".format(registroAluno[2]))
        print("3ª Nota: {}".format(registroAluno[3]))
        print("4ª Nota: {}".format(registroAluno[4]))
        print("Média: {}".format(registroAluno[17]))
        print("Matemática:")
        print("1ª Nota: {}".format(registroAluno[5]))
        print("2ª Nota: {}".format(registroAluno[6]))
        print("3ª Nota: {}".format(registroAluno[7]))
        print("4ª Nota: {}".format(registroAluno[8]))
        print("Média: {}".format(registroAluno[18]))
        print("Geografia:")
        print("1ª Nota: {}".format(registroAluno[9]))
        print("2ª Nota: {}".format(registroAluno[10]))
        print("3ª Nota: {}".format(registroAluno[11]))
        print("4ª Nota: {}".format(registroAluno[12]))
        print("Média: {}".format(registroAluno[19]))
        print("História:")
        print("1ª Nota: {}".format(registroAluno[13]))
        print("2ª Nota: {}".format(registroAluno[14]))
        print("3ª Nota: {}".format(registroAluno[15]))
        print("4ª Nota: {}".format(registroAluno[16]))
        print("Média: {}".format(registroAluno[20]))     
        print('--'*26)
    print('Retornando ao menu anterior...') 
    import coordenadorPedagogico
    coordenadorPedagogico.menuEstatisticasAlunos()   
def estatisticasTerceiroAnoC():
    import sqlite3
    conectar = sqlite3.connect("bancodeDados.db") 
    interagir = conectar.cursor() 
    for registroAluno in interagir.execute("SELECT * FROM terceiroanoc ORDER by nomealuno"):
        print('Nome do aluno(a): {}'.format(registroAluno[0]))        
        print("Português:")
        print("1ª Nota: {}".format(registroAluno[1]))
        print("2ª Nota: {}".format(registroAluno[2]))
        print("3ª Nota: {}".format(registroAluno[3]))
        print("4ª Nota: {}".format(registroAluno[4]))
        print("Média: {}".format(registroAluno[17]))
        print("Matemática:")
        print("1ª Nota: {}".format(registroAluno[5]))
        print("2ª Nota: {}".format(registroAluno[6]))
        print("3ª Nota: {}".format(registroAluno[7]))
        print("4ª Nota: {}".format(registroAluno[8]))
        print("Média: {}".format(registroAluno[18]))
        print("Geografia:")
        print("1ª Nota: {}".format(registroAluno[9]))
        print("2ª Nota: {}".format(registroAluno[10]))
        print("3ª Nota: {}".format(registroAluno[11]))
        print("4ª Nota: {}".format(registroAluno[12]))
        print("Média: {}".format(registroAluno[19]))
        print("História:")
        print("1ª Nota: {}".format(registroAluno[13]))
        print("2ª Nota: {}".format(registroAluno[14]))
        print("3ª Nota: {}".format(registroAluno[15]))
        print("4ª Nota: {}".format(registroAluno[16]))
        print("Média: {}".format(registroAluno[20]))     
        print('--'*26)
    print('Retornando ao menu anterior...')
    import coordenadorPedagogico
    coordenadorPedagogico.menuEstatisticasAlunos()              